---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: dnf-autoupdate-centos
    image: quay.io/centos/centos:stream8
    pre_build_image: false
    command: /sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
