---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
