---

name: ansible tests

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: >
          pip3 install
          ansible
          ansible-lint
          yamllint
          molecule
          molecule-docker

      - name: reset molecule
        run: molecule reset

      - name: test playbook
        run: molecule test --driver-name docker
